##### LEARNING_PARAMETER #######################################################################
epochs                          = 10000
batch_size                      = 32
learning_rate                   = 0.0001
learning_rate_decay             = 0.999
seed                            = 1234
##### CHECKPOINT_SETTING #######################################################################
load_checkpoint_name            = ""
save_checkpoint_name            = "TORCH_TEST"
save_checkpoint_period          = 1
##### MODEL_PARAMETER ##########################################################################
past_size                       = 2200
present_size                    = 1600
future_size                     = 2200
dilation                        = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
shift_size                      = 1600
sampling_rate                   = 16000
input_window                    = 'uniform'
output_window                   = 'uniform'
##### DATASET_PATH #############################################################################
train_noisy_path                = "/home/server7/DATASET/woman_4noise/noisy"
train_orig_path                 = "/home/server7/DATASET/woman_4noise/orig"
test_noisy_path                 = "/home/server7/DATASET/woman_4noise/noisy"
test_orig_path                  = "/home/server7/DATASET/woman_4noise/orig"
##### NEPTUNE_SETTING ##########################################################################
project_name                    = 'csp-lab/AEC'
model_name                      = "TORCH_TEST"
api_key_name                    = 'yjc'
backup_file_list                = ['train.py', 'model.py', 'config.py', 'loss_function.py']